apiVersion: apps/v1
kind: Deployment
metadata:
  name: minecraft
  labels:
    app: minecraft
spec:
  selector:
    matchLabels:
      app: minecraft
  replicas: 1
  template:
    metadata:
      labels:
        app: minecraft
    spec:
      containers:
        - name: minecraft
          image: itzg/minecraft-server:java11
          ports:
            - containerPort: 25565
          env:
            - name: EULA
              value: "true"
            - name: TYPE
              value: spigot
            - name: VERSION
              value: "1.16.4"
---
apiVersion: v1
kind: Service
metadata:
  name: minecraft
spec:
  type: NodePort
  ports:
    - port: 25565
      nodePort: 25565
  selector:
    app: minecraft
