name: benchmark-latex-build

on:
  workflow_dispatch:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        foo: ["", "bar"]
        bar: ["foo", ""]
        docker-tag: ["v1.4.0"]
    steps:
      - name: pull image
        run: docker pull ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }}
      - name: print some stuff
        run: echo "::set-output name=out-${{ matrix.docker-tag }}-${{ matrix.foo != "" }}-${{ matrix.bar != "" }}::${{ matrix.foo }}${{ matrix.bar }}"
  # results:
  #   runs-on: ubuntu-latest
  #   needs: benchmark
  #   steps:
  #     - name: get results
  #       run: echo ${{ needs.benchmark.outputs.out-v1.4.0--foo }}
