name: benchmark-latex-build

on:
  workflow_dispatch:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        disable-diffpdf: ["", "1"]
        disable-synctex: ["1"]
        disable-pythontex: ["1"]
        docker-tag: ["v1.4.0"]
    steps:
      - name: pull image
        run: docker pull ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }}
      - name: clone repo
        run: git clone https://github.com/DSczyrba/Vorlage-Latex
      - name: set key
        run: echo "key=${{ matrix.docker-tag }},${{ matrix.disable-diffpdf != '' }},${{ matrix.disable-synctex != '' }},${{ matrix.disable-pythontex != '' }}" >> $GITHUB_ENV
      - name: benchmark
        run: |
          echo ---
          bash -c "for i in {0..1}; do docker run -u $(id -u ${USER}):$(id -g ${USER}) --rm -v \"$(pwd)/Vorlage-Latex/Latex:/latex\" ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }}; rm -rf Vorlage-Latex/Latex/.build; done"
          echo ---
          /usr/bin/time -f %e bash -c "for i in {0..1}; do docker run -u $(id -u ${USER}):$(id -g ${USER}) --rm -v \"$(pwd)/Vorlage-Latex/Latex:/latex\" ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }}; rm -rf Vorlage-Latex/Latex/.build; done"
          echo ---
          echo elapsed=$(/usr/bin/time -f %e bash -c "for i in {0..1}; do docker run -u $(id -u ${USER}):$(id -g ${USER}) --rm -v \"$(pwd)/Vorlage-Latex/Latex:/latex\" ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }}; rm -rf Vorlage-Latex/Latex/.build; done") >> $GITHUB_ENV
          echo ${{ env.key }},$elapsed > result.csv
          echo ${{ env.key }},$elapsed
      - name: upload result
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.key }}
          path: result.csv
  prepare-results:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - name: download artifacts
        uses: actions/download-artifact@v2
      - name: aggregate results
        run: find /home/runner/work/test/test -type f ! -name 'results.csv' -exec cat {} + > results.csv
      - name: upload super-results
        uses: actions/upload-artifact@v2
        with:
          name: results
          path: results.csv
