name: benchmark-latex-build

on:
  workflow_dispatch:
  push:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        disable-diffpdf: ["", "1"]
        disable-synctex: ["", "1"]
        disable-pythontex: ["", "1"]
        docker-tag: ["v1.4.0"]
    steps:
      - name: pull image
        run: docker pull ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }}
      - name: clone repo
        run: git clone https://github.com/DSczyrba/Vorlage-Latex
      - name: benchmark
        run: echo ::set-output name=out-$(echo ${{ matrix.docker-tag }} | tr . -)-${{ matrix.disable-diffpdf != '' }}-${{ matrix.disable-synctex != '' }}-${{ matrix.disable-pythontex != '' }}::$(/usr/bin/time -f %e bash -c "for i in {0..1}; do docker run -u $(id -u ${USER}):$(id -g ${USER}) --rm -v \"$(pwd)/Vorlage-Latex/Latex:/latex\" ghcr.io/jemand771/latex-build:${{ matrix.docker-tag }} &> /dev/null; rm -rf Vorlage-Latex/Latex/.build; done")
  results:
    runs-on: ubuntu-latest
    needs: benchmark
    steps:
      - name: get results
        run: |
          echo "${{ needs.benchmark.outputs.v1-4-0-true-true-true }}"
