name: test contains function

on:
  push:

env:
  my_var: |
    hello
    world

jobs:
  foo:
    runs-on: ubuntu-latest
    steps:
      - name: run echo
        run: |
          echo hello: ${{ contains(env.my_var, 'hello') }}
          echo hello with nl: ${{ contains(env.my_var, 'hello\r\n') }}
          echo world: ${{ contains(env.my_var, 'world') }}
          echo world with nl: ${{ contains(env.my_var, 'world\r\n') }}
          echo 123: ${{ contains(env.my_var, '123') }}
          echo 123 with nl: ${{ contains(env.my_var, '123\r\n') }}
