name: context-test

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  print:
    runs-on: ubuntu-latest
    steps:
      - if: ${{ github.event_name == 'push' }}
        run: |
          echo "${{ github.event.before }} -> ${{ github.event.after }}"
      - if: ${{ github.event_name == 'pull_request' }}
        run: |
          echo "${{ github.event.pull_request.base.ref }} -> ${{ github.event.pull_request.head.ref }} (changes to, not a merge arrow)"
