name: Deploy

on:
  pull_request:

jobs:
  deploy:
    name: Deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        with:
          token: ${{ github.token }}
          initial-status: pending
