name: Deploy

on:
  pull_request:
  issue_comment:
    types:
      - created

jobs:
  deploy:
    if: github.event.sender.login == github.repository_owner && (github.event_name == 'pull_request' || github.event.issue.pull_request && github.event.comment.body == '/deploy')
    name: Deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: chrnorm/deployment-action@v2
        name: Create GitHub deployment
        with:
          token: ${{ github.token }}
          initial-status: pending
          environment: preview-${{ github.event.number }}
