name: Deploy

on:
  - pull_request

jobs:
  deploy:
    name: Deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - uses: bobheadxi/deployments@v1
        name: Create GitHub deployment
        with:
          token: ${{ github.token }}
          env: preview-${{ github.event.number }}
          step: start
