name: Undeploy

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Undeploy preview
    runs-on: ubuntu-latest

    steps:
      - name: Mark GitHub deployment inactive
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ secrets.DEPLOY_TOKEN }}
          environment: preview-${{ github.event.number }}
          onlyDeactivateDeployments: true
