name: Undeploy

on:
  pull_request:
    types:
      - closed

jobs:
  deploy:
    name: Deploy preview
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Mark GitHub deployment inactive
        uses: strumwolf/delete-deployment-environment@v2
        with:
          token: ${{ github.token }}
          environment: preview-${{ github.event.number }}
          onlyDeactivateDeployments: true
