name: docker-meta

on:
  push:
    branches:
      - "main"
      - "dev"
    tags:
      - "v*.*.*"
  workflow_dispatch:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ghcr.io/jemand771/latex-build
          flavor: |
            latest=false
          tags: |
            type=semver,pattern=v{{version}}
            type=raw,enable=${{ github.ref == 'refs/heads/main' }},value=latest
            type=raw,enable=${{ github.ref == 'refs/heads/dev' }},value=experimental
      - name: print some stuff
        run: echo ${{ github.ref }}  ${{ steps.meta.output.tags }}